# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create Report

on:
  push:
    branches: [ main ]
    paths: [ "./**/*.py", "*.py", "*.md" ]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.3.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      run: python test.py
    - name: Update README
      run: cp Report.md README.md
    - name: Create PDF report
      run: npx md-to-pdf --pdf-options "{\"format\":\"A4\",\"margin\":\"20mm\",\"printBackground\":true}" Report.md
    - name: Update Report in static folder
      run: cp Report.pdf ./static/files/Report.pdf
    - name: Add & Commit
      uses: EndBug/add-and-commit@v7.2.1
      with:
        message: "Update results"
        
        
